create database inovide;
use database inovide;


create table Iuser(
     id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     username varchar(255) NOT NULL,
     email varchar(255) NOT NULL,
     passwword password NOT NULL,
     firstname varchar(255) NOT NULL,
     lastname varchar(255) NOT NULL,
     imagedirectory varchar(255),
     followers integer ,
     creditcard varchar(60)
);

create table Icomment(
     id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     ideaid integer,
     data varchar(255) NOT NULL,
     datee date NOT NULL,
     commentorid integer
);

create table Iideas(
     id integer REFERENCES Iresource(idealid) ON UPDATE CASCADE ON      DELETE CASCADE,
ideaownerid integer REFERENCES Iresource(ownerid) ON UPDATE CASCADE ON DELETE CASCADE,
     data varchar(255) NOT NULL,
     datee date NOT NULL,
     title varchar(255) NOT NULL,
     discription varchar(255) NOT NULL,
     visiblity char(2),
     novote integer ,
     nocomment integer
);

create table Iresource(
     idealid integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     ownerid integer,
     directory varchar(255) NOT NULL
);

create table Ifollowing(
     id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     followerid integer,
     followedid integer
);

create table Imessage(
     id integer REFERENCES Imessageresource(messageid) ON UPDATE CASCADE ON      DELETE CASCADE,
     senderid integer,
     receiverid integer,
     text varchar(255) NOT NULL,
     datee date NOT NULL,
     seen boolean
);

create table Imessageresource(
     id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     messageid integer,
     directory varchar(255) NOT NULL
);

create table Ialies(
     id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     userid integer,
     alieid varchar(255) NOT NULL
);


